# Jekyll config file http://jekyllrb.com/docs/configuration/

# Handling reading
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - key.asc
  - src
  - package.json
  - Gruntfile.js
  - vendor
  - bower.json
encoding: "utf-8"

# Plugins
gems:
#  - jekyll-feed
#  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

# jekyll-mentions:
#  base_url: https://twitter.com

# Conversion
markdown:     kramdown
kramdown:
  toc_levels: 1..3
highlighter:  pygments

# Outputting
permalink:     /:year/:title/
paginate_path: /page:num/
paginate:      5
timezone:      Asia/Kathmandu
locale:        en_us

# Serving, does not include hostname
baseurl: ""

# URL of site, include http://, do not include a trailing slash
url: "http://milanaryal.com"

# Site settings
name:             EuRED tech blog
description:      "Reading experiences, database, TEI and so many things"
icon:             "/assets/img/m-icon-white-on-blue.png"
featured_image:   "/assets/img/home-bg.jpg"
theme_color:      "#2196f3"
author:
  name:           Gautier Michelin
  email:          "gm@ideesculture.com"
  uri:            "https://twitter.com/gautiermichelin"
  twitter:        gautiermichelin
  github:         eured
  street:         Campus Universitaire
  locality:       Le Mans
  country:        France
  postcode:       72000

# Google Analytics
# !! Current Tracking ID only for milanaryal.com !!
google_analytics_id: "UA-42092423-1"

# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: "true"

# Compress HTML
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
